#!/bin/bash

list=(
bash-comkpletion
kitty
ranger
python-pillow #image preview
mc
feh
pcmanfm-gtk3
file-roller
polkit
tree
reflector
htop
arandr
)


for name in "${list[@]}" ; do
sudo pacman -S --noconfirm --needed $name
done
